---
deployment:
  tasks:
    - export PUBLIC_PATH=/home/c6743/public_html
    - export LARAVEL_BACKEND_PATH=/home/c6743
    - /bin/cp -r ./app $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./bootstrap $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./config $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./database $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./public_html $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./resources $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./routes $LARAVEL_BACKEND_PATH
    - /bin/cp -r ./storage $LARAVEL_BACKEND_PATH
    - /bin/cp ./artisan $LARAVEL_BACKEND_PATH
    - /bin/cp ./composer.json $LARAVEL_BACKEND_PATH
    - cd $LARAVEL_BACKEND_PATH
